### ISSUE TITLE
Reflections no longer working in mathematics/parametric-surfaces

### ISSUE THREAD

**Issue by paulmasson** [exploratoria/exploratoria.github.io#13]
@theo-armour 

And no error messages either. When this happened in AlgeSurf it was a CORS issue with a clear error message.

Any ideas?

**Comment by theo-armour** [comment]
@paulmasson 

It's always a good idea - especially in issues - to include a link to the matter at hand.

I can find many links to my many efforts - most of which are broken. 

Even better, many efforts seem to be broken or no longer working - but in so many ways

Perhaps the interesting conjecture revolves more on the topic of whether you have found anything that works?

**Comment by paulmasson** [comment]
Your reply was not helpful.

**Comment by theo-armour** [comment]
@paulmasson 

Ah, now it looks like you found it and fixed it.
