### ISSUE TITLE
the content must be served over HTTPS

### ISSUE THREAD

**Issue by evdem** [exploratoria/exploratoria.github.io#15]
Please set HTTPS for the links
<script src=http://exploratoria.github.io/lib/reader/readme-reader.js></script>
I see this error e.g. at
https://exploratoria.github.io/cookbook/models/index.html

**Comment by paulmasson** [comment]
@evdem thanks for catching this! I think I got all the links needing update, but let me know if you find any others. Please be aware that pages in this part of the repository were old works in progress and may not function completely.

**Comment by evdem** [comment]
"can't save the file" in Chrome
https://github.com/exploratoria/exploratoria.github.io/tree/master/templates/
<a href="http://exploratoria.github.io/templates/index.html" title="View file as a web page"

**Comment by paulmasson** [comment]
@evdem with latest Chrome on Windows 10 the save file feature works for me. The file goes automatically to my Downloads folder without the option to choose the location. If this is not the same for you, please be more specific.
