### ISSUE TITLE
Labels for Issues

### ISSUE THREAD

**Issue by theo-armour** [exploratoria/exploratoria.github.io#6]
@paulmasson 

If we are to use the GitHub issues feature as a significant means of communication the we should set up some labels (categories ) for issues.

I suggest at least the following to start:
- Strategy
- Bug
- Enhancement
- Help
- Question
- Suggestion

**Comment by paulmasson** [comment]
Sounds good to me. There are already some labels available: did you create these or are they default? And what about coloring?

**Comment by theo-armour** [comment]
@paulmasson 

Labels edited.

To edit labels, go to

https://github.com/exploratoria/exploratoria.github.io/issues

click 'labels' - to right of filters box

**Comment by theo-armour** [comment]
Add link, update label
